name:                language-vhdl-quote
version:             0.1.0.0
github:              "truls/language-vhdl-quote"
license:             LGPL-3
author:              "Truls Asheim"
maintainer:          "truls@asheim.dk"
copyright:           "Truls Asheim 2018"

extra-source-files:
- README.md
- test/vests/Makefile
- test/vests/*.sh
- test/vests/LICENSE
- test/vests/COPYING
- test/vests/README
- test/vests/suite.tar.xz

# Metadata used when publishing your package
synopsis:            VHDL quasiquoting library
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/truls/language-vhdl-quote#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wnoncanonical-monad-instances
  - -Wnoncanonical-monadfail-instances
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -O2
  #- -O0

dependencies:
 - base   >=4 && <5
 - megaparsec >= 6.5.0
 - here >= 1.2.11
 - template-haskell >= 2.11.1.0
 - mtl >= 2.2.1
 - haskell-src-meta >= 0.8.0.1
 - syb >= 0.7
 - unordered-containers >= 0.2.8.0
 # Remove extra-deps from stack.yaml at som point
 - mainland-pretty >= 0.7
 - text >= 1.2.2.2
 - pretty-show >= 1.6.13
 - tasty >= 0.11.3
 - tasty-hunit >= 0.9.2

library:
  source-dirs: src

executables:
  dumpast:
    main: dumpast.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-vhdl-quote
      - directory
  vhdlgen:
    main: vhdlgen.hs
    source-dirs: examples
    dependencies:
      - language-vhdl-quote

tests:
  vests:
    main: vests.hs
    source-dirs: test
    dependencies:
      - process >= 1.6.1.0
      - language-vhdl-quote
      - filemanip >= 0.3.6.3
      - directory >= 1.3.0.2
      - extra >= 1.6.6

  antiquote-tests:
    main:                aqtest.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-vhdl-quote
